development:
    adapter: postgresql
    database: pcj_db
    host: localhost
    port: 5433
    username: cers
    password: 'c3r$-d8'
    uri: mongodb://localhost/development
    mongodb_logger:
        database: kurumi_logger
        capsize: <% 250.megabytes %>

production:
    adapter: postgresql
    database: pcj_db
    host: localhost
    port: 5433
    username: cers
    password: 'c3r$-d8'
    uri: mongodb://10.0.3.179/kurumi
